# Generated by Django 5.1.3 on 2024-12-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role_user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
