# Generated by Django 5.1.4 on 2024-12-09 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0003_delete_mambaling_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mambaling',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mambaling_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
