# Generated by Django 5.1.4 on 2024-12-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0007_clearancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to='profile_pictures/'),
        ),
    ]
