# Generated by Django 5.1.4 on 2024-12-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0008_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
