# Generated by Django 5.1.4 on 2024-12-28 04:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0009_clearancerequest_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearancerequest',
            name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='clearancerequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='clearancerequest',
            name='type',
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='birthdate',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='birthplace',
            field=models.CharField(default='profile_photos/default_profile.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='block_number',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='civil_status',
            field=models.CharField(default='Not Specified', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='contact',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='document_type',
            field=models.CharField(default='Identity Card', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='occupation',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default_profile.png', upload_to='profile_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='proof_of_residency',
            field=models.FileField(default='proof_of_residency/default_residency.pdf', upload_to='proof_of_residency/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='purpose',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
