# Generated by Django 5.1.4 on 2024-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0011_clearancerequest_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='residency_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clearancerequest',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clearancerequest',
            name='document_type',
            field=models.CharField(choices=[('Barangay Clearance', 'Barangay Clearance'), ('Certificate of Indigency', 'Certificate of Indigency'), ('Certificate of Residency', 'Certificate of Residency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clearancerequest',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
