# Generated by Django 5.1.4 on 2024-12-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0012_clearancerequest_decline_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfResidency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='proof_of_residency/')),
                ('clearance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_files', to='mambaling.clearancerequest')),
            ],
        ),
    ]
