# Generated by Django 5.1.4 on 2025-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mambaling', '0014_alter_clearancerequest_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofresidency',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_residency/'),
        ),
    ]
